id: I09721679
ocr_import_info:
  source: bdrc
  software: google_books
  batch: batch_2022
  expected_default_language: bo
  bdrc_scan_id: W30151
  ocr_info:
    timestamp: 03/21/23T14:00:30
    html: html.zip
    txt: txt.zip
    images: images.zip
  op_import_options: {}
  op_import_version: 0.11.9
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2024-02-28 21:07:56.551212+00:00
last_modified: 2024-02-28 21:07:56.551219+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W30151
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW30151
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཁལ་ཁ་རྗེ་བཙུན་དམ་པ་སྐུ་ཕྲེང་རིམ་བྱོན་གྱི་རྣམ་ཐར།
  languages:
  - bo
  author: ཁལ་ཁ་རྗེ་བཙུན་དམ་པ ༠༡་བློ་བཟང་བསྟན་པའི་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.9333048826629827
  ocr_word_median_confidence_index: 1.0
bases:
  I5923:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5923
      total_pages: 804
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5923.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9333048826629827
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
